#!/usr/bin/env bash

echo "Running ler-opt compiler..."

OPTIMIZED="optimized.ler"
CONVERTED="converted.ler"

if [ $# -eq 0 ]
then
	echo "Please provide a filename for compilation!"
fi

filename=$1
shift
compile_args=("$@")

# Run optimizer
java optimizer.Glory $filename > $OPTIMIZED

# Convert notation
python3 notation_converter.py $OPTIMIZED $CONVERTED

# Run compiler
./ler-compile $CONVERTED ${compile_args[@]}

rm $OPTIMIZED
# rm $CONVERTED
